# Generated by Django 6.1.1 on 2026-09-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m'),
        ),
    ]
